services:
  # neo4j:
  #   image: neo4j:5.22-community
  #   container_name: neo4j
  #   ports: [ "7474:7474", "7687:7687" ]
  #   environment:
  #     - NEO4J_AUTH=neo4j/neo4j_password
  #     - NEO4J_server_memory_heap_initial__size=1G
  #     - NEO4J_server_memory_heap_max__size=2G
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: [ "11434:11434" ]
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_USE_GPU=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  neo4j_data:
  neo4j_logs:
  ollama:
